[package]
name = "Mixer"
version = "1.0.0"

[dependencies]
# This line tells the compiler we are using the official Aptos framework
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "devnet" }

[addresses]
# This line creates a named address 'veil_addr'. We will set its
# value in the next step.
mixer = "0x2267d403073795ada7cb1da76029e92c2b0b693ecfbdc31e1ea65c57584d33bd"
